# Generated by Django 5.1.1 on 2024-11-28 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "Description",
                    models.TextField(blank=True, max_length=1024, null=True),
                ),
                ("Photo", models.ImageField(blank=True, null=True, upload_to="albums")),
                ("Left", models.BooleanField()),
                ("Right", models.BooleanField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "Description",
                    models.TextField(blank=True, max_length=1024, null=True),
                ),
                ("Photo", models.ImageField(blank=True, null=True, upload_to="albums")),
                ("Left", models.BooleanField()),
                ("Right", models.BooleanField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Factory", models.CharField(blank=True, max_length=70, null=True)),
                ("Phone", models.CharField(blank=True, max_length=70, null=True)),
                ("Email", models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=100, null=True)),
                ("Subject", models.CharField(blank=True, max_length=200, null=True)),
                ("Phone", models.CharField(blank=True, max_length=70, null=True)),
                ("Email", models.CharField(blank=True, max_length=70, null=True)),
                ("Message", models.TextField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "Description",
                    models.TextField(blank=True, max_length=1024, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "Description",
                    models.TextField(blank=True, max_length=1024, null=True),
                ),
                ("Photo", models.ImageField(blank=True, null=True, upload_to="albums")),
                ("Left", models.BooleanField()),
                ("Right", models.BooleanField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Title",
                    models.CharField(blank=True, default="", max_length=70, null=True),
                ),
                (
                    "Description",
                    models.TextField(blank=True, max_length=2048, null=True),
                ),
                ("Photo", models.ImageField(blank=True, null=True, upload_to="albums")),
                ("Left", models.BooleanField()),
                ("Right", models.BooleanField()),
                ("Middle", models.BooleanField()),
                ("Empty", models.BooleanField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "Blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="strona.blog"
                    ),
                ),
            ],
        ),
    ]
