# Generated by Django 5.1.1 on 2024-12-05 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("strona", "0002_delete_offers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="Blog",
            new_name="blog",
        ),
    ]
