# Generated by Django 5.1.1 on 2024-12-05 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("strona", "0003_rename_blog_post_blog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="blog",
            new_name="Blog",
        ),
    ]
