# Generated by Django 5.1.1 on 2024-12-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strona", "0004_rename_blog_post_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Left",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="Right",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="Empty",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="Left",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="Middle",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="Right",
            field=models.BooleanField(null=True),
        ),
    ]
